chat:
  globalPrefix: "|"
  spectator:
    see: true
    talk: true

eventName: "Vexian UHC S4"

game:
  markers:
    gentlemenDuration: 1
    episodeDuration: 1

  teamSize: 4

  start:
    countDownLength: 10
    resistanceLength: 20

death:
  delay: 10