chat:
  globalPrefix: "|"
  listPlayers:
    seeTeammateDetails: true

  spectator:
    see: true
    talk: true

death:
  delay: 10

eventName: "Vexian UHC S4"

game:
  environment:
    worldborder:
      enable: true

      initialSize: 25
      endSize: 10

      shrink:
        enable: true

        delay: 0
        time: 5
      warning:
        type: "distance"
        amount: 10

  markers:
    episodeDuration: 20
    gentlemenDuration: 10
    worldborder:
      start: true
      progress: 1
      end: true

  teamSize: 4

  start:
    countDownLength: 10
    resistanceLength: 20