name: NuzlockeUHC
version: 0.1
description: Helps organize UHC events, Pokémon style.
author: PhotonBurst

main: st.photonbur.UHC.Nuzlocke.Nuzlocke
website: https://github.com/PhotonBursted/Vaks-UHC

commands:
  deregister:
    description: Unregisters a player out of the match.
    permission: Nuzlocke.startMatch
  list:
    description: Lists all players.
    permission: Nuzlocke.startMatch
  getSpecial:
    description: Redeems reward when conditions are met
    permission: Nuzlocke.startMatch
  register:
    description: Registers a player into playing the match.
    permission: Nuzlocke.startMatch
  startMatch:
    description: Regulates hug parties. Oh, also, UHC events.
    permission: Nuzlocke.startMatch
  stopMatch:
    description: Stops the quarrel.
    permission: Nuzlocke.startMatch

permissions:
  Nuzlocke.*:
    description: Grants access to all commands in VaksUHC.
    children:
      Nuzlocke.startMatch: true
  Nuzlocke.startMatch:
    description: Allows the starting of a match
    default: true